# Generated by Django 4.2.11 on 2024-04-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='int',
            new_name='price',
        ),
    ]
