# Generated by Django 4.2.11 on 2024-04-08 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malls.customer')),
                ('ordered_customers', models.ManyToManyField(related_name='ordered_customers', to='malls.customer')),
                ('ordered_products', models.ManyToManyField(related_name='ordered_products', to='malls.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malls.product')),
            ],
        ),
    ]
