# Generated by Django 4.2.11 on 2024-04-08 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_customers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_products',
        ),
    ]
