# Generated by Django 4.2.9 on 2024-04-09 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subcription',
            field=models.ManyToManyField(related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
