# Generated by Django 4.2.11 on 2024-04-09 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='subscribed_users',
            field=models.ManyToManyField(related_name='subscribed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
