# Generated by Django 4.2.11 on 2024-04-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_author_subscribed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='subscribed_users',
        ),
    ]
