# Generated by Django 4.2.9 on 2024-04-08 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='user',
            new_name='like_users',
        ),
    ]
