# Generated by Django 4.2.11 on 2024-04-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
