# Generated by Django 4.2.11 on 2024-04-19 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='like_users',
            field=models.ManyToManyField(null=True, related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
