# Generated by Django 4.2.11 on 2024-04-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance')], default='Comedy', max_length=10),
        ),
    ]
