# Generated by Django 4.2.11 on 2024-04-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
